variables:
  CROWDIN_PROJECT_ID: $CROWDIN_PROJECT_ID
  CROWDIN_PERSONAL_TOKEN: $CROWDIN_PERSONAL_TOKEN

stages:
  - translations
  - publish

publish_gem:
  image: ruby
  stage: publish
  script:
    - echo "---" > .credentials
    - |
      echo ":ci_rubygems_api_key: $GEM_HOST_API_KEY" >> .credentials
    - chmod 0600 .credentials
    - gem build decidim-decidim_geo.gemspec
    - gem push decidim-decidim_geo-*.gem -k ci_rubygems_api_key --config-file .credentials
  only:
    - tags

upload-translations:
  stage: translations
  image: node:16.18
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  script:
    - npm install -g @crowdin/cli
    - crowdin upload --no-progress
    - crowdin status --no-progress

# Create a MR with the new translation
mr-translations:
  stage: translations
  image: node:16.18
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - export BRANCH_NAME="i18n/$(date +%Y%m%d%H%M%S)"
    - export ORIGIN="crowndin_$(date +%Y%m%d%H%M%S)"
    - npm install -g @crowdin/cli
    - crowdin download --no-progress
    - git checkout -b $BRANCH_NAME
    - git add config/locales
    - if git diff-index --quiet HEAD --; then
        echo "Nothing to commit. Aborting.";
        exit 0;
      fi
    - git config --global user.email "mr-translations"
    - git config --global user.name "$GIT_USERNAME"
    - echo "add $ORIGIN=https://$GIT_USERNAME:$ACCESS_TOKEN@git.octree.ch/decidim/decidim-module-geo.git"
    - git remote add $ORIGIN https://$GIT_USERNAME:$ACCESS_TOKEN@git.octree.ch/decidim/decidim-module-geo.git
    - git commit -m "Update translations"
    - git push $ORIGIN HEAD:$BRANCH_NAME -o merge_request.create -o merge_request.target=main
