include:
  - project: o/infra/templates
    file: /gitlab-ci/includes/jobs.yaml

development-app:026:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    DECIDIM_VERSION: '0.26'
  script:
    - echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - COMMIT="${CI_COMMIT_TAG:-$CI_COMMIT_SHA}"
    - REG=$CI_REGISTRY_IMAGE
    - CONTEXT="$CI_PROJECT_DIR"
    - REP_GRP="decidim-geo-$DECIDIM_VERSION"
    - /kaniko/executor 
      --context "$CONTEXT" 
      --dockerfile "$CONTEXT/Dockerfile" 
      --destination $REG/$REP_GRP:$COMMIT 
      --destination $REG/$REP_GRP:latest 
      --verbosity=error
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /v.*$/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
